services:
  - type: web
    name: akilli-ev-sistemi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ANA_SUNUCU_URL
        value: http://ana-sunucu-url:10000
      - key: API_ANAHTAR
        value: akilli_ev_gizli_anahtar
      - key: EMAIL_KULLANICI
        value: herdemerasmus@gmail.com
      - key: EMAIL_SIFRE
        value: kmop hzuo yoqp ztnr
      - key: EMAIL_ALICI
        value: hidayete369@gmail.com
